### ISSUE TITLE
Udp broadcast support

### ISSUE THREAD

**Issue by lorismich** [Wiznet/RP2040-HAT-MicroPython#9]
The module turns on and I am able to receive an address via DHCP but when I try to initialize a UDP socket to transmit a broadcast package I received an error:

>[code]>> import socket
>>> socket.SOL_SOCKET
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SOL_SOCKET'[/code]

Why SOL_SOCKET isn't defined ? I also tried with usocket module with the same result:

[code]>>> import usocket
>>> usocket.SOL_SOCKET
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SOL_SOCKET'[/code]

**Comment by simryang** [comment]
For my cases, it works. Which version do you use?
I used [W5100S_EVB_PICO-20230426-v1.20.0.uf2](https://github.com/wiznetmaker/RP2040-PicoBricks-HAT-Micropython/blob/main/pico_uf2/W5100S_EVB_PICO-20230426-v1.20.0.uf2) file from https://micropython.org/download/W5100S_EVB_PICO/

```python3
>>> import usocket
>>> print(usocket, type(usocket))
<module 'lwip'> <class 'module'>
>>> print(dir(usocket))
['__class__', '__name__', '__dict__', 'AF_INET', 'AF_INET6', 'IPPROTO_IP', 'IP_ADD_MEMBERSHIP', 'IP_DROP_MEMBERSHIP', 'SOCK_DGRAM', 'SOCK_RAW', 'SOCK_STREAM', 'SOL_SOCKET', 'SO_REUSEADDR', 'callback', 'getaddrinfo', 'print_pcbs', 'reset', 'socket']
>>> print(usocket.SOL_SOCKET)
1
```
